name: saxswaxs
channels:
  - astra-toolbox
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - chessanalysispipeline=0.0.11
  - matplotlib
  - nexusformat
  - numpy
  - pydantic<2.0
  - pyfai
  - pip==22.3.1
  - pip:
    - certif-pyspec==1.5.3
