name: saxswaxs
channels:
  - astra-toolbox
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - chessanalysispipeline=0.0.11
  - matplotlib
  - nexusformat
  - numpy
  - pydantic<2.0
  - pyfai
  - certif-pyspec
